# Generated by Django 2.2.2 on 2019-06-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='post',
        ),
    ]
